dist: xenial
os:
  - linux
  - osx

language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-9
    - openssl
    - zlib1g-dev
    - libgsl-dev
    - libfftw3-dev
    - libnetcdf-dev

  homebrew:
    packages:
    - cmake
    - gcc@9
    - zlib
    - openssl
    - gsl
    - fftw
    - netcdf

before_script:
  - export CC=gcc-9 CXX=g++-9

script:
  - |
    root=$(pwd);
    compressors=("blosc" "fpzip" "isabela" "sz" "zfp");
    for current in "${compressors[@]}"; do
      cd ${current} && mkdir build && cd build;
      cmake -DCMAKE_INSTALL_PREFIX=../install ..;
      make -j && make install && cd ${root};
    done
